#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-Simple
Version  : 1.001014
Release  : 8
URL      : http://www.cpan.org/CPAN/authors/id/E/EX/EXODIST/Test-Simple-1.001014.tar.gz
Source0  : http://www.cpan.org/CPAN/authors/id/E/EX/EXODIST/Test-Simple-1.001014.tar.gz
Summary  : 'Basic utilities for writing tests.'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Test-Simple-doc

%description
writing tests, by Michael G Schwern <schwern@pobox.com>. Maintained by Chad
Granum <exodist@cpan.org>.

%package doc
Summary: doc components for the perl-Test-Simple package.
Group: Documentation

%description doc
doc components for the perl-Test-Simple package.


%prep
%setup -q -n Test-Simple-1.001014

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/Test/Builder.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Builder/IO/Scalar.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Builder/Module.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Builder/Tester.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Builder/Tester/Color.pm
/usr/lib/perl5/site_perl/5.22.0/Test/More.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Simple.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Tester.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Tester/Capture.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Tester/CaptureRunner.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Tester/Delegate.pm
/usr/lib/perl5/site_perl/5.22.0/Test/Tutorial.pod
/usr/lib/perl5/site_perl/5.22.0/Test/use/ok.pm
/usr/lib/perl5/site_perl/5.22.0/ok.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
